### ISSUE TITLE
CentOS support

### ISSUE THREAD

**Issue by eronlloyd** [SonarSoftware/poller#1]
We're primarily a RHEL/CentOS shop, and need to deploy poller servers in each of our networks. Right now we're running on the default Ubuntu setup, but I've been experimenting with porting the code to RHEL. I've been able to get very close in terms of package translation to standard distro RPMs, as well as config file and path tweaks, but still not working.

I think it would be great if we could have packaging for both Ubuntu and RHEL/CentOS, especially for enterprise service providers that depend on RHEL platforms. I'm happy to help get this ported, but still will need to rely on Sonar for official support in keeping it up to date moving forward.

**Comment by SonarSoftware** [comment]
Eron,

What's blocking it working on CentOS today? I don't think there's anything Ubuntu specific in it, the instructions are just tailored to it as a default.

**Comment by SonarSoftware** [comment]
Eron,

The only thing I could find was the hardcoded path to fping, I've added this as an .env variable in 1.1.0. Let me know if there's anything else you need here.

**Comment by eronlloyd** [comment]
Thanks @SonarSoftware. We're going to spin up a VM to test the new release. I have notes on the problems we faced and will update and share afterwards.
